Feature/deactivate account fix
uwcirg/isacc-messaging-service pull request #56
Opened 2023-12-14 00:16 UTC by Filienko

Creating CLI commands to disable and enable active.

2023-12-28 02:55 UTC, pbugni requested changes

2023-12-28 02:55 UTC, pbugni commented on isacc_messaging/api/isacc_record_creator.py
> +            error = "No patient with this phone number"
trailing whitespace?

2023-12-28 02:55 UTC, pbugni commented on isacc_messaging/models/isacc_patient.py
> +        NB, returns only patients with active set to true
i see no check for active here, as the comment suggests?

2023-12-28 02:55 UTC, pbugni commented on isacc_messaging/models/isacc_patient.py
> +
again, i don't see any code checking for active patients.

2024-01-12 02:09 UTC, pbugni requested changes

2024-01-12 02:09 UTC, pbugni commented on isacc_messaging/api/views.py
> +    for json_patient in next_in_bundle(active_patients):
why not just search for the single patient by given id?

2024-01-12 02:09 UTC, pbugni commented on isacc_messaging/api/views.py
> +        f"Patient with id {patient.id} reinstated",
audit's are intended for paper trail.  i'd expect this CLI is typically only going to be used once - when this feature is turned on.  i'd suggest "Patient {patient.id} active set true" or the like.

2024-01-18 00:14 UTC, pbugni requested changes
This looks good, but I'm concerned about `on_twilio_message_received()`

We don't include the `active` check when looking up a patient there, so if there happens to be 2 patients with the same phone number, `first_in_bundle()` could give you the in-active one.

I think you should modify the query there, and remove the `pt.active` checks below there.

2024-01-18 18:12 UTC, pbugni requested changes
one minor nit to fix.

2024-01-18 18:12 UTC, pbugni commented on isacc_messaging/api/isacc_record_creator.py
> +            return "Need active patient"
i realize this is just a change from before, but this is close to an unnecessary check.  if we're going to check for a required parameter and it isn't there or valid, please raise an exception.

2024-01-18 18:51 UTC, achen2401 commented on isacc_messaging/models/isacc_patient.py
>          response = HAPI_request('GET', 'Patient')
@Filienko Do you know if this does indeed return **all** the patients or does it return paginated results?  For instance, I think we had to loop through all pages to get at all the CommunicationRequest resources when sending out email notifications (see [here](https://github.com/uwcirg/isacc-messaging-service/blob/00473047a1dd25e203b01645638d0276cf676c47/isacc_messaging/api/isacc_record_creator.py#L422)).  I am not certain if we need to consider the same, i.e. pagination, here.

2024-01-18 19:31 UTC, achen2401 approved these changes

2024-01-19 00:38 UTC, pbugni approved these changes

2024-01-19 00:58 UTC, merged